ReceptionBundle\Entity\Soiree:
    type: entity
    table: null
    repositoryClass: ReceptionBundle\Repository\SoireeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        descriptif:
            type: string
            length: 255
        photo:
            type: string
            length: 255
        dateInvitation:
            type: datetime

    manyToMany:
        soiree:
            targetEntity: UserBundle\Entity\User
            inversedBy: user
            joinTable:
                name: participation_users
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    soiree_id:
                        referencedColumnName: id
