soiree_index:
    path:     /
    defaults: { _controller: "ReceptionBundle:Soiree:index" }
    methods:  GET

soiree_show:
    path:     /{id}/show
    defaults: { _controller: "ReceptionBundle:Soiree:show" }
    methods:  GET

soiree_new:
    path:     /new
    defaults: { _controller: "ReceptionBundle:Soiree:new" }
    methods:  [GET, POST]

soiree_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReceptionBundle:Soiree:edit" }
    methods:  [GET, POST]

soiree_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReceptionBundle:Soiree:delete" }
    methods:  DELETE
