home:
    resource: "@ReceptionBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#user:
    #resource: "@UserBundle/Resources/config/routing.yml"
    #prefix:   /

#reception:
    #resource: "@UserBundle/Resources/config/routing.yml"
    #prefix:   /