home:
    resource: "@ReceptionBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path:     /
    defaults: { _controller: ReceptionBundle:Default:index }

#user:
    #resource: "@UserBundle/Resources/config/routing.yml"
    #prefix:   /

#reception:
    #resource: "@UserBundle/Resources/config/routing.yml"
    #prefix:   /
